file:
  directory: D:/2024-02/download/tdd

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/acamatchtest
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: green502

#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
