constant:
  address-const:
    start-sep: "@"
    end-sep: "#"
    detail-address-sep: detail
    post-num-sep: post

#API 사용하려고
  post-address-api-const:
    base-url: https://api.odsay.com/v2/api # 얘는 나중에 git올리기전 빼고
    search-pub-trans-path-url: /local/search/address.json?query=우편번호
    param-api-key-name: apiKey
    param-api-key-value: GxXDL514Ds52H/04R8HPPo+2TZlcR7sQrmNnwb8+Sxw

  info-const:
    title: JWT Practice
    description: JWT + Security 고도화
    version: v0.1

  email-const:
    base-url: http://localhost:8080
    url: user/complete-sign-up
    key: token
    template-name: emailTemplate
    expired-time: 900_000
    subject: ACAMATCH 회원가입
    alias: AcaMatch
    from-email: 0ca2sa0@gmail.com

  user-const:
    user-pic-file-path: /user/%d # %d는 유저 아이디 값이 들어갈 자리

  jwt-const:
    issuer: green@green.kr #토큰 발행자
    secret: bwrahkgtfjhewsghjvbhjavfhyjaeswgjbeshjabhjewbvnmbdhjtgfvrehjbmfnxdzbhjlgnb
    header-key: Authorization
    claim-key: signedUser
    bearer-format: JWT
    scheme: Bearer
    access-token-expiry: 600_000 #10분 (MS)
    refresh-token-expiry: 1_296_000_000 # 15일 (MS)
    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-expiry: 1_296_000 #15일 (S)

file:
  directory: D:/LJY/GreenGramTdd/image

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: studyBridge
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/acamatch
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 15MB

  # API때문에 이걸로 바꿈
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${constant.email-const.from-email}
    password: wotrvbcpartvbbmk
    properties:
      mail:
        smtp:
          auth: true  # SMTP 인증 사용
          starttls:
            enable: true

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    path: /swagger
    operations-sorter: method
    tags-sorter: alpha
  cache:
    disabled: true