constant:
  address-const:
    start-sep: "@"
    end-sep: "#"
    detail-address-sep: detail
    post-num-sep: post
  api-const:
    api-key: sk-svcacct-cypWCFbSA26kot7wBIEeiYgB_z1JKWr-UgnLrzROTJ-DJAt9ng5LCLFCi7K8HN9qYoNzIcT3BlbkFJmAfc2cveEr_hfhnfSSdZbbUyDSU-ZXN1tVdYDiU8junu5C90Y9-gz11upsLEmpF7qfIboA

  info-const:
    title: AcaMatch
    description: AcaMatch
    version: v0.1

  email-const:
    base-url: http://localhost:8080
    sign-up-url: api/user/sign-up
    temp-pw-url: api/user/temp-pw
    token-key: token
    pk-key: pk
    sign-up-template-name: emailTemplate
    find-pw-template-name: pwEmailTemplate
    expired-time: 900_000
    sign-up-subject: ACAMATCH 회원가입
    find-pw-subject: ACAMATCH 비밀번호 찾기
    alias: AcaMatch
    from-email: 0ca2sa0@gmail.com

  user-const:
    user-pic-file-path: /user/%d # %d는 유저 아이디 값이 들어갈 자리
    redirect-url: /

  jwt-const:
    issuer: green@green.kr #토큰 발행자
    secret: bwrahkgtfjhewsghjvbhjavfhyjaeswgjbeshjabhjewbvnmbdhjtgfvrehjbmfnxdzbhjlgnb
    header-key: Authorization
    claim-key: signedUser
    bearer-format: JWT
    scheme: Bearer
    access-token-expiry: 600_000 #10분 (MS) -> 1시간으로 교체
    refresh-token-expiry: 1_296_000_000 # 15일 (MS)
    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-expiry: 1_296_000 #15일 (S)

file:
  directory: D:/LJY/GreenGramTdd/image

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: AcaMatch
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/acamatch
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 150MB

  # API때문에 이걸로 바꿈
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${constant.email-const.from-email}
    password: wotrvbcpartvbbmk
    properties:
      mail:
        smtp:
          auth: true  # SMTP 인증 사용
          starttls:
            enable: true

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    path: /swagger
    operations-sorter: method
    tags-sorter: alpha
  cache:
    disabled: true