constant:
  server-const:
    server-url: http://112.222.157.156:5223

file:
  directory: /home/download/image

spring:
  datasource:
      url: jdbc:log4jdbc:mariadb://192.168.0.144/db_even_second_3
      username: even_second_3
      password: electro