constant:
  email-const:
    base-url: http://112.222.157.157:5233

file:
  directory: /home/download/image

spring:
  datasource:
      url: jdbc:log4jdbc:mariadb://192.168.0.144/db_even_last_3
      username: even_last_3
      password: exynos
  jpa:
    hibernate:
      ddl-auto: create-drop