version: "3.8"

services:
  backend:
    image: my-backend-image  # 실제 사용하는 이미지 이름으로 변경
    container_name: my-backend-container  # 컨테이너 이름
    ports:
      - "8080:5223"  # 필요한 포트 매핑
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # prod 환경 설정
      - FILE_DIRECTORY=/home/download/image  # Docker 내부 저장 경로 (application-prod.yaml에서 사용)
      - EXCEL_FILE_PATH=/app/temp/student_grades.xlsx  # Docker 내부 엑셀 파일 경로
    volumes:
      - D:/GSY/excelFile:/home/download/image  # 기존 이미지 저장 경로
      - D:/GSY/excelFile/excel:/app/temp  # 엑셀 파일이 저장될 로컬 폴더 마운트